# Generated by Django 6.0.7 on 2026-08-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('student_name', models.CharField(max_length=100)),
                ('msg', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
