# Generated by Django 6.0.7 on 2026-08-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0002_parentregistration_delete_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentregistration',
            old_name='msg',
            new_name='address',
        ),
    ]
