# Generated by Django 6.0.7 on 2026-08-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0003_rename_msg_parentregistration_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentregistration',
            old_name='phone',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='parentregistration',
            old_name='name',
            new_name='parent_name',
        ),
        migrations.AlterField(
            model_name='parentregistration',
            name='address',
            field=models.TextField(),
        ),
    ]
